;/*FB_PKG_DELIM*/

__d("CometAlbumLeftRailFallback.react",["CometColumn.react","CometColumnItem.react","CometLeftRailComponent.react","CometLeftRailHeader.react","FDSGlimmer.react","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u={buttonGlimmer:{borderStartStartRadius:"x1i5p2am",borderStartEndRadius:"x1whfx0g",borderEndEndRadius:"xr2y4jy",borderEndStartRadius:"x1ihp6rs",height:"x1vqgdyp",$$css:!0},formElementGlimmer:{borderStartStartRadius:"x1i5p2am",borderStartEndRadius:"x1whfx0g",borderEndEndRadius:"xr2y4jy",borderEndStartRadius:"x1ihp6rs",height:"xnnlda6",$$css:!0},privacyScopeGlimmer:{borderStartStartRadius:"x1i5p2am",borderStartEndRadius:"x1whfx0g",borderEndEndRadius:"xr2y4jy",borderEndStartRadius:"x1ihp6rs",height:"x1s1d1n7",width:"xafpxmx",$$css:!0}};function c(e){var t=o("react-compiler-runtime").c(8),n=e.title,a;t[0]===Symbol.for("react.memo_cache_sentinel")?(a=s.jsx("div",{className:"x1wdk0sc xyamay9 xv54qhq x1l90r2v xf7dkkf",children:s.jsx(r("FDSGlimmer.react"),{index:1,xstyle:u.buttonGlimmer})}),t[0]=a):a=t[0];var i;t[1]!==n?(i=s.jsx(r("CometLeftRailHeader.react"),{title:n}),t[1]=n,t[2]=i):i=t[2];var l;t[3]===Symbol.for("react.memo_cache_sentinel")?(l=s.jsx(r("CometColumnItem.react"),{children:s.jsx(r("FDSGlimmer.react"),{index:0,xstyle:u.privacyScopeGlimmer})}),t[3]=l):l=t[3];var c;t[4]===Symbol.for("react.memo_cache_sentinel")?(c=s.jsx(r("CometColumnItem.react"),{children:s.jsx(r("FDSGlimmer.react"),{index:0,xstyle:u.formElementGlimmer})}),t[4]=c):c=t[4];var d;t[5]===Symbol.for("react.memo_cache_sentinel")?(d=s.jsxs(r("CometColumn.react"),{paddingHorizontal:16,spacing:16,children:[l,c,s.jsx(r("CometColumnItem.react"),{children:s.jsx(r("FDSGlimmer.react"),{index:0,xstyle:u.buttonGlimmer})})]}),t[5]=d):d=t[5];var m;return t[6]!==i?(m=s.jsx(r("CometLeftRailComponent.react"),{footer:a,header:i,primaryNav:d}),t[6]=i,t[7]=m):m=t[7],m}l.default=c}),98);
__d("CometAlbumMediaAttachmentNullState.react",["fbt","FDSGlimmer.react","FDSNullState.react","NullStateMedia","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l,s){"use strict";var e,u=e||(e=o("react")),c={glimmer:{borderStartStartRadius:"x1i5p2am",borderStartEndRadius:"x1whfx0g",borderEndEndRadius:"xr2y4jy",borderEndStartRadius:"x1ihp6rs",height:"x1vd4hg5",width:"x1e5gqux",$$css:!0}};function d(e){var t=o("react-compiler-runtime").c(6),n=e.disableVideo,a=e.isReady,i=a===void 0?!0:a,l;t[0]!==n?(l=n===!0?s._(/*BTDS*/"Drag photos here to get started."):s._(/*BTDS*/"Drag photos and videos here to get started."),t[0]=n,t[1]=l):l=t[1];var d=l,m;t[2]===Symbol.for("react.memo_cache_sentinel")?(m={className:"x6s0dn4 x78zum5 x5yr21d xl56j7k"},t[2]=m):m=t[2];var p;return t[3]!==d||t[4]!==i?(p=u.jsx("div",babelHelpers.extends({},m,{children:i?u.jsx(r("FDSNullState.react"),{body:d,headline:s._(/*BTDS*/"Ready to add something?"),icon:r("NullStateMedia")}):u.jsx(r("FDSGlimmer.react"),{index:0,xstyle:c.glimmer})})),t[3]=d,t[4]=i,t[5]=p):p=t[5],p}l.default=d}),226);
__d("CometAlbumMediaAttachmentFullscreenNullState.react",["CometAlbumMediaAttachmentNullState.react","gkx","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=r("gkx")("21034");function c(e){var t=o("react-compiler-runtime").c(5),n=e.disableVideo,a=e.isReady,i,l;t[0]===Symbol.for("react.memo_cache_sentinel")?(i={0:{className:"x6s0dn4 x78zum5 x1q1vt7x xl56j7k"},1:{className:"x6s0dn4 x78zum5 xl56j7k x1xzm4ny x5yr21d"}}[!!u<<0],l={className:"x1ajlkzm xzk7aed"},t[0]=i,t[1]=l):(i=t[0],l=t[1]);var c;return t[2]!==n||t[3]!==a?(c=s.jsx("div",babelHelpers.extends({},i,{children:s.jsx("div",babelHelpers.extends({},l,{children:s.jsx(r("CometAlbumMediaAttachmentNullState.react"),{disableVideo:n,isReady:a})}))})),t[2]=n,t[3]=a,t[4]=c):c=t[4],c}l.default=c}),98);
__d("CometPhotoAlbumCreateQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="31699477686364655"}),null);
__d("CometPhotoAlbumCreateQuery$Parameters",["CometPhotoAlbumCreateQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CometPhotoAlbumCreateQuery_facebookRelayOperation"),metadata:{},name:"CometPhotoAlbumCreateQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CometPhotoAlbumCreateRoot.entrypoint",["CometPhotoAlbumCreateQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(){return{queries:{CometPhotoAlbumCreateQueryReference:{parameters:n("CometPhotoAlbumCreateQuery$Parameters"),variables:{privacySelectorRenderLocation:"COMET_ALBUM",scale:o("WebPixelRatio").get()}}}}},root:r("JSResourceForInteraction")("CometPhotoAlbumCreateRoot.react").__setRef("CometPhotoAlbumCreateRoot.entrypoint")},s=e;l.default=s}),98);
__d("FDSPlusOutline24Icon",["cr:14237"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14237")}),98);
__d("FDSPlusOutline24PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("483773"),24),u=e;l.default=u}),98);
__d("UFACCodedErrorUtils",[],(function(t,n,r,o,a,i){"use strict";function e(e){var t=e;return t.code!=null&&t.description!=null&&t.summary!=null?t:null}i.coerceToCodedError=e}),66);