;/*FB_PKG_DELIM*/

__d("CometUnifiedShareSheetEmbedVideoContentQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="9702573803157362"}),null);
__d("CometUnifiedShareSheetEmbedVideoContentQuery$Parameters",["CometUnifiedShareSheetEmbedVideoContentQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CometUnifiedShareSheetEmbedVideoContentQuery_facebookRelayOperation"),metadata:{},name:"CometUnifiedShareSheetEmbedVideoContentQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CometEmbedVideoDialog.entrypoint",["CometUnifiedShareSheetEmbedVideoContentQuery$Parameters","JSResourceForInteraction"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.videoID;return{extraProps:{videoID:e},queries:{embedVideoQueryReference:{parameters:n("CometUnifiedShareSheetEmbedVideoContentQuery$Parameters"),variables:{videoID:e}}}}},root:r("JSResourceForInteraction")("CometEmbedVideoDialogRoot.react").__setRef("CometEmbedVideoDialog.entrypoint")};l.default=e}),98);
__d("CometFeedStoryMenuOriginalStoryIDContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext(null);l.default=u}),98);
__d("FDSArrowsSquareAddFilled24Icon",["cr:14443"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14443")}),98);
__d("XCometCreatorCollaborationInviteControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/collaboration_invite/{video_id}/{secondary_collaborator_id}/",Object.freeze({}),void 0),s=e;l.default=s}),98);
__d("XCometProfessionalDashboardCollaborationHomeControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/professional_dashboard/collaborations/",Object.freeze({}),void 0),s=e;l.default=s}),98);
__d("groupsCometDeleteNodeFromConnection",["CometRelay","RelayFBConnectionHandler"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t,n,r){var a,i=e.get(t);i!=null&&((a=o("RelayFBConnectionHandler").getAllConnectionsWithKey(e,i,r))!=null?a:[]).forEach(function(e){return o("CometRelay").ConnectionHandler.deleteNode(e,n)})}l.default=e}),98);
__d("useCometEmbedVideo",["CometEmbedVideoDialog.entrypoint","react","react-compiler-runtime","useCometEntryPointDialog"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=o("react"))).useRef;function u(e){var t=o("react-compiler-runtime").c(7),n=e.clickPoint,a=e.videoID,i;t[0]!==a?(i={videoID:a},t[0]=a,t[1]=i):i=t[1];var l=i,u=s(null),c=r("useCometEntryPointDialog")(r("CometEmbedVideoDialog.entrypoint"),l),d=c[0],m;t[2]!==n||t[3]!==d?(m=function(){d({clickPoint:n})},t[2]=n,t[3]=d,t[4]=m):m=t[4];var p=m,_;return t[5]!==p?(_={onClick:p,triggerRef:u},t[5]=p,t[6]=_):_=t[6],_}l.default=u}),98);
__d("viewerContentUpdaterUtils",["CometRelay"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t,n,r){var a=e.get(t);if(a!=null){var i;r==="PENDING"?i=o("CometRelay").ConnectionHandler.getConnection(n,"GroupsCometViewerContentPendingPostsFeed_stories",{content_type:r,ordering:"NEWEST_FIRST"}):r==="PUBLISHED"&&(i=o("CometRelay").ConnectionHandler.getConnection(n,"GroupsCometViewerContentPublishedPostsFeed_stories",{content_type:r,ordering:"NEWEST_FIRST"})),i!=null&&o("CometRelay").ConnectionHandler.insertEdgeBefore(i,a)}}function s(e,t,n){var r,o=t.getDataID(),a=(r=e.get(o))==null?void 0:r.getLinkedRecord("stories",{content_type:n});if(a!=null){var i=a.getDataID(),l=e.get(i);if(l!=null){var s=l.getValue("count_up_to",{max:51});typeof s=="number"&&l.setValue(Math.max(s-1,0),"count_up_to",{max:51});var u=l.getValue("count_up_to",{max:1});typeof u=="number"&&typeof s=="number"&&s-1===0&&l.setValue(Math.max(u-1,0),"count_up_to",{max:1})}}}l.addEdgeToViewerContentConnection=e,l.decrementSectionCounts=s}),98);
__d("viewerContentPendingPostUpdater",["CometRelay","groupsCometDeleteNodeFromConnection","viewerContentUpdaterUtils"],(function(t,n,r,o,a,i,l){"use strict";function e(e){var t=e.groupID,n=e.store,a=e.storyID;if(t!=null){var i=n.get(t);if(i!=null){var l=i.getLinkedRecord("viewer_content");if(l!=null){var s=l.getDataID();r("groupsCometDeleteNodeFromConnection")(n,s,a,"GroupsCometViewerContentPendingPostsFeed_stories"),o("viewerContentUpdaterUtils").decrementSectionCounts(n,l,"PENDING")}}}}function s(e,t){return function(n){if(t!=null){var r=n.get(e);if(r!=null){var a=r.getLinkedRecord("viewer_content");if(a!=null){var i=o("CometRelay").ConnectionHandler.getConnection(a,"GroupsCometViewerContentPendingPostsFeed_stories",{content_type:"PENDING",ordering:"NEWEST_FIRST"});i!=null&&o("CometRelay").ConnectionHandler.insertEdgeBefore(i,t)}}}}}l.viewerContentDeletePendingPostUpdater=e,l.viewerContentAddPendingPostUpdater=s}),98);